### ISSUE TITLE
add a avg load pic

### ISSUE THREAD

**Issue by coderall** [yangoliver/mydoc#1]
Hi oliver,could you add the xmind pic within the following URL to this repository 
[阿里杨勇：浅谈 Linux 高负载的系统化分析](https://mp.weixin.qq.com/s?__biz=MzAwMDUwNDgxOA==&mid=2652662968&idx=1&sn=3c2ddc2f47fe8804de1f8407f11ef81d)
![image](https://user-images.githubusercontent.com/10015677/33824612-f34b663a-de99-11e7-82e3-d32b5d123c52.png)

**Comment by yangoliver** [comment]
@coderall 

Sorry for late response.

Please find the svg file from,

https://github.com/yangoliver/mydoc/blob/master/share/picture/loadavg_debug.svg
